#!/usr/bin/env bash
#
# End-to-end tests for the Appflight Bitrise step.
#
# Each case runs step.sh exactly as Bitrise would (inputs as environment
# variables, BITRISE_DEPLOY_DIR set) against a throwaway copy of a fixture, and
# asserts on the step's exit code, its log, and the JSON artifact it writes.
#
# Usage:
#   ./test/run-tests.sh            # real CLI, installs the pinned version once
#   FAST=1 ./test/run-tests.sh     # reuse the appflight already on PATH

set -uo pipefail

readonly TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly REPO_DIR="$(cd "${TEST_DIR}/.." && pwd)"
readonly STEP="${REPO_DIR}/step.sh"
readonly PINNED_VERSION="0.8.0"

pass_count=0
fail_count=0

green() { printf '\033[32m%s\033[0m\n' "$*"; }
red()   { printf '\033[31m%s\033[0m\n' "$*"; }
bold()  { printf '\033[1m%s\033[0m\n' "$*"; }

ok()      { green "  PASS  $*"; pass_count=$((pass_count + 1)); }
notok()   { red   "  FAIL  $*"; fail_count=$((fail_count + 1)); }

assert_eq() {
  local expected="$1" actual="$2" what="$3"
  if [ "$expected" = "$actual" ]; then
    ok "${what} (= ${actual})"
  else
    notok "${what}: expected '${expected}', got '${actual}'"
  fi
}

assert_contains() {
  local haystack="$1" needle="$2" what="$3"
  if printf '%s' "$haystack" | grep -qF -- "$needle"; then
    ok "${what}"
  else
    notok "${what}: log did not contain '${needle}'"
  fi
}

assert_file() {
  if [ -s "$1" ]; then ok "$2"; else notok "$2: no non-empty file at $1"; fi
}

assert_no_file() {
  if [ ! -e "$1" ]; then ok "$2"; else notok "$2: unexpected file at $1"; fi
}

# The critical fixture needs a live-looking credential to prove the scanner
# catches one. That literal is ASSEMBLED HERE and written into the throwaway
# workspace at test time — it is deliberately never committed. A repo whose
# whole purpose is catching hardcoded secrets must not contain one, and a
# committed secret-shaped literal also trips GitHub push protection.
# The parts are kept separate so no contiguous match exists in this file.
readonly SECRET_PREFIX="sk_live"
readonly SECRET_BODY="A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6"
readonly FAKE_SECRET="${SECRET_PREFIX}_${SECRET_BODY}"

# Fresh copy of a fixture so cache dirs never pollute the committed tree.
make_workspace() {
  local fixture="$1"
  local workspace
  workspace="$(mktemp -d)"
  cp -R "${TEST_DIR}/fixtures/${fixture}" "${workspace}/app"
  if [ "$fixture" = "critical-app" ]; then
    cat >"${workspace}/app/Sources/Configuration.swift" <<SWIFT
import Foundation

enum Configuration {
    // Generated by the test harness. Appflight reports this as CRITICAL
    // under guideline 1.6 and redacts the value in its own output.
    static let paymentSecret = "${FAKE_SECRET}"

    static let apiBaseURL = URL(string: "https://api.example.com")!
}
SWIFT
  fi
  printf '%s' "$workspace"
}

# Runs step.sh, capturing combined output and exit code into globals.
run_step() {
  STEP_OUT="$(env "$@" bash "$STEP" 2>&1)"
  STEP_STATUS=$?
}

json_field() {
  node -e '
    const fs = require("fs");
    try {
      const r = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
      const path = process.argv[2].split(".");
      let v = r;
      for (const k of path) v = v?.[k];
      process.stdout.write(String(v));
    } catch { process.stdout.write("PARSE_ERROR"); }
  ' "$1" "$2" 2>/dev/null
}

skip_install_flag() {
  if [ "${FAST:-0}" = "1" ]; then echo "APPFLIGHT_STEP_SKIP_INSTALL=true"; else echo "APPFLIGHT_STEP_SKIP_INSTALL=false"; fi
}

bold "Appflight Bitrise step — end-to-end tests"
echo "step:   ${STEP}"
echo "pinned: ${PINNED_VERSION}"
echo "mode:   $([ "${FAST:-0}" = "1" ] && echo 'FAST (reuse PATH binary)' || echo 'full (npm install per case)')"
echo

# ─────────────────────────────────────────────────────────────────────────────
bold "1. Clean project passes and still writes the artifact"
ws="$(make_workspace clean-app)"
run_step "$(skip_install_flag)" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  fail_on="critical" \
  deep="false" \
  api_token=""

assert_eq 0 "$STEP_STATUS" "step exits 0"
assert_contains "$STEP_OUT" "PASSED" "log reports PASSED"
assert_file "${ws}/deploy/appflight-report.json" "JSON artifact written"
assert_eq "0" "$(json_field "${ws}/deploy/appflight-report.json" summary.total)" "report total is 0"
assert_eq "false" "$(json_field "${ws}/deploy/appflight-report.json" gate.triggered)" "gate not triggered"
assert_contains "$STEP_OUT" "APPFLIGHT_FINDING_COUNT=0" "finding count exported"
assert_contains "$STEP_OUT" "data boundary: local only" "local-only boundary stated"
rm -rf "$ws"
echo

# ─────────────────────────────────────────────────────────────────────────────
bold "2. Critical finding fails the build with exit 1"
ws="$(make_workspace critical-app)"
run_step "$(skip_install_flag)" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  fail_on="critical" \
  deep="false" \
  api_token=""

assert_eq 1 "$STEP_STATUS" "step exits 1"
assert_contains "$STEP_OUT" "FAILED — findings at or above" "log reports the gate failing"
assert_contains "$STEP_OUT" "compliance gate working as configured" "failure is attributed to the gate"
assert_file "${ws}/deploy/appflight-report.json" "JSON artifact written on failure"
assert_eq "1" "$(json_field "${ws}/deploy/appflight-report.json" summary.total)" "report total is 1"
assert_eq "1" "$(json_field "${ws}/deploy/appflight-report.json" summary.critical)" "report critical is 1"
assert_eq "true" "$(json_field "${ws}/deploy/appflight-report.json" gate.triggered)" "gate triggered"
assert_contains "$STEP_OUT" "APPFLIGHT_FINDING_COUNT=1" "finding count exported on failure"
# The secret must never appear in the log or the artifact.
assert_contains "$STEP_OUT" "[REDACTED]" "secret is redacted in the log"
if grep -qF "$FAKE_SECRET" "${ws}/deploy/appflight-report.json"; then
  notok "raw secret leaked into the JSON artifact"
else
  ok "raw secret absent from the JSON artifact"
fi
rm -rf "$ws"
echo

# ─────────────────────────────────────────────────────────────────────────────
bold "3. fail_on=none is report-only: findings recorded, build still passes"
ws="$(make_workspace critical-app)"
run_step "$(skip_install_flag)" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  fail_on="none" \
  deep="false" \
  api_token=""

assert_eq 0 "$STEP_STATUS" "step exits 0 with fail_on=none"
assert_file "${ws}/deploy/appflight-report.json" "artifact still written"
assert_eq "1" "$(json_field "${ws}/deploy/appflight-report.json" summary.critical)" "critical finding still recorded"
rm -rf "$ws"
echo

# ─────────────────────────────────────────────────────────────────────────────
bold "4. deep=true without a token fails fast"
ws="$(make_workspace clean-app)"
run_step "$(skip_install_flag)" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  fail_on="critical" \
  deep="true" \
  api_token=""

assert_eq 1 "$STEP_STATUS" "step exits 1"
assert_contains "$STEP_OUT" "deep is 'true' but api_token is empty" "explains the misconfiguration"
assert_contains "$STEP_OUT" "appflight login --print-token" "tells the user how to get a token"
assert_no_file "${ws}/deploy/appflight-report.json" "no artifact written on a config error"
rm -rf "$ws"
echo

# ─────────────────────────────────────────────────────────────────────────────
bold "4b. deep=true rejects unresolved or malformed secret values"
ws="$(make_workspace clean-app)"

run_step "$(skip_install_flag)" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  fail_on="critical" \
  deep="true" \
  api_token='$APPFLIGHT_API_TOKEN'

assert_eq 1 "$STEP_STATUS" "unexpanded secret reference exits 1"
assert_contains "$STEP_OUT" "unexpanded environment-variable reference" "identifies Bitrise secret expansion"
assert_contains "$STEP_OUT" "Replace variables in inputs" "gives the Bitrise setting to enable"
assert_no_file "${ws}/deploy/appflight-report.json" "no artifact written for an unresolved secret"

run_step "$(skip_install_flag)" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  fail_on="critical" \
  deep="true" \
  api_token="not-an-appflight-token"

assert_eq 1 "$STEP_STATUS" "malformed token exits 1"
assert_contains "$STEP_OUT" "raw three-part token" "explains the accepted token shape"
rm -rf "$ws"
echo

bold "5. Invalid configuration is rejected before install"
ws="$(make_workspace clean-app)"

run_step BITRISE_DEPLOY_DIR="${ws}/deploy" project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" fail_on="banana" deep="false" api_token=""
assert_eq 1 "$STEP_STATUS" "bad fail_on exits 1"
assert_contains "$STEP_OUT" "fail_on must be one of" "names the valid values"

run_step BITRISE_DEPLOY_DIR="${ws}/deploy" project_path="${ws}/app" \
  appflight_version="latest" fail_on="critical" deep="false" api_token=""
assert_eq 1 "$STEP_STATUS" "appflight_version=latest is rejected"
assert_contains "$STEP_OUT" "must be an exact version" "explains why pinning is required"

run_step BITRISE_DEPLOY_DIR="${ws}/deploy" project_path="${ws}/does-not-exist" \
  appflight_version="$PINNED_VERSION" fail_on="critical" deep="false" api_token=""
assert_eq 1 "$STEP_STATUS" "missing project_path exits 1"
assert_contains "$STEP_OUT" "is not a directory" "explains the bad path"

run_step BITRISE_DEPLOY_DIR="${ws}/deploy" project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" fail_on="critical" deep="maybe" api_token=""
assert_eq 1 "$STEP_STATUS" "bad deep value exits 1"
rm -rf "$ws"
echo

# ─────────────────────────────────────────────────────────────────────────────
bold "6. CLI exit 2 fails the build as a TOOL ERROR, never as clean"
ws="$(make_workspace clean-app)"
stub_dir="${ws}/stub"
mkdir -p "$stub_dir"
cat >"${stub_dir}/appflight" <<'STUB'
#!/usr/bin/env bash
# Stands in for a CLI that cannot complete the scan.
if [ "$1" = "version" ]; then echo "0.8.0"; exit 0; fi
echo "appflight check: scan failed: simulated tool error" >&2
exit 2
STUB
chmod +x "${stub_dir}/appflight"

run_step APPFLIGHT_STEP_SKIP_INSTALL=true \
  PATH="${stub_dir}:${PATH}" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  fail_on="critical" \
  deep="false" \
  api_token=""

assert_eq 1 "$STEP_STATUS" "tool error fails the build"
assert_contains "$STEP_OUT" "TOOL ERROR" "distinct TOOL ERROR label"
assert_contains "$STEP_OUT" "must not be read as one" "explicitly warns against reading it as clean"
assert_contains "$STEP_OUT" "APPFLIGHT_FINDING_COUNT=unknown" "finding count is 'unknown', not 0"
assert_no_file "${ws}/deploy/appflight-report.json" "empty report is removed, not left as a stub"
rm -rf "$ws"
echo

# ─────────────────────────────────────────────────────────────────────────────
bold "6b. deep=true injects api_token as APPFLIGHT_TOKEN for the CLI only"
ws="$(make_workspace clean-app)"
stub_dir="${ws}/stub"
mkdir -p "$stub_dir"
cat >"${stub_dir}/appflight" <<'STUB'
#!/usr/bin/env bash
if [ "$1" = "version" ]; then echo "0.8.0"; exit 0; fi
case " $* " in
  *" --deep "*)
    if [ "${APPFLIGHT_TOKEN:-}" != "header.payload.signature" ]; then
      echo "missing command-scoped APPFLIGHT_TOKEN" >&2
      exit 2
    fi
    printf '%s\n' '{"summary":{"total":0},"gate":{"triggered":false}}'
    ;;
  *)
    echo "deterministic stub"
    ;;
esac
exit 0
STUB
chmod +x "${stub_dir}/appflight"

run_step APPFLIGHT_STEP_SKIP_INSTALL=true \
  PATH="${stub_dir}:${PATH}" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  fail_on="critical" \
  deep="true" \
  api_token="header.payload.signature"

assert_eq 0 "$STEP_STATUS" "valid deep credential reaches the CLI"
assert_file "${ws}/deploy/appflight-report.json" "deep JSON artifact written"
assert_eq "0" "$(json_field "${ws}/deploy/appflight-report.json" summary.total)" "deep report is parsed"
rm -rf "$ws"
echo

bold "7. Missing BITRISE_DEPLOY_DIR degrades with a warning"
ws="$(make_workspace clean-app)"
pushd "$ws" >/dev/null
run_step "$(skip_install_flag)" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  fail_on="critical" \
  deep="false" \
  api_token=""
popd >/dev/null

assert_eq 0 "$STEP_STATUS" "step still completes"
assert_contains "$STEP_OUT" "BITRISE_DEPLOY_DIR is not set" "warns the artifact will not be exported"
rm -rf "$ws"
echo

# ─────────────────────────────────────────────────────────────────────────────
rule="========================================================"
echo "$rule"
if [ "$fail_count" -eq 0 ]; then
  green "ALL ASSERTIONS PASSED  (${pass_count} assertions)"
  echo "$rule"
  exit 0
fi
red "FAILURES: ${fail_count} failed, ${pass_count} passed"
echo "$rule"
exit 1
