#!/usr/bin/env bash
#
# End-to-end tests for the Appflight Bitrise step.
#
# Each case runs step.sh exactly as Bitrise would (inputs as environment
# variables, BITRISE_DEPLOY_DIR set) against a throwaway copy of a fixture, and
# asserts on the step's exit code, its log, and the JSON artifact it writes.
#
# Usage:
#   ./test/run-tests.sh            # real CLI, installs the pinned version once
#   FAST=1 ./test/run-tests.sh     # reuse the appflight already on PATH

set -uo pipefail

readonly TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly REPO_DIR="$(cd "${TEST_DIR}/.." && pwd)"
readonly STEP="${REPO_DIR}/step.sh"
readonly PINNED_VERSION="0.12.0"

pass_count=0
fail_count=0

green() { printf '\033[32m%s\033[0m\n' "$*"; }
red()   { printf '\033[31m%s\033[0m\n' "$*"; }
bold()  { printf '\033[1m%s\033[0m\n' "$*"; }

ok()      { green "  PASS  $*"; pass_count=$((pass_count + 1)); }
notok()   { red   "  FAIL  $*"; fail_count=$((fail_count + 1)); }

assert_eq() {
  local expected="$1" actual="$2" what="$3"
  if [ "$expected" = "$actual" ]; then
    ok "${what} (= ${actual})"
  else
    notok "${what}: expected '${expected}', got '${actual}'"
  fi
}

assert_contains() {
  local haystack="$1" needle="$2" what="$3"
  if printf '%s' "$haystack" | grep -qF -- "$needle"; then
    ok "${what}"
  else
    notok "${what}: log did not contain '${needle}'"
  fi
}

assert_not_contains() {
  local haystack="$1" needle="$2" what="$3"
  if printf '%s' "$haystack" | grep -qF -- "$needle"; then
    notok "${what}: log unexpectedly contained '${needle}'"
  else
    ok "${what}"
  fi
}

assert_file() {
  if [ -s "$1" ]; then ok "$2"; else notok "$2: no non-empty file at $1"; fi
}

assert_no_file() {
  if [ ! -e "$1" ]; then ok "$2"; else notok "$2: unexpected file at $1"; fi
}

# The critical fixture needs a live-looking credential to prove the scanner
# catches one. That literal is ASSEMBLED HERE and written into the throwaway
# workspace at test time — it is deliberately never committed. A repo whose
# whole purpose is catching hardcoded secrets must not contain one, and a
# committed secret-shaped literal also trips GitHub push protection.
# The parts are kept separate so no contiguous match exists in this file.
readonly SECRET_PREFIX="sk_live"
readonly SECRET_BODY="A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6"
readonly FAKE_SECRET="${SECRET_PREFIX}_${SECRET_BODY}"

# Fresh copy of a fixture so cache dirs never pollute the committed tree.
make_workspace() {
  local fixture="$1"
  local workspace
  workspace="$(mktemp -d)"
  cp -R "${TEST_DIR}/fixtures/${fixture}" "${workspace}/app"
  if [ "$fixture" = "critical-app" ]; then
    cat >"${workspace}/app/Sources/Configuration.swift" <<SWIFT
import Foundation

enum Configuration {
    // Generated by the test harness. Appflight reports this as CRITICAL
    // under guideline 1.6 and redacts the value in its own output.
    static let paymentSecret = "${FAKE_SECRET}"

    static let apiBaseURL = URL(string: "https://api.example.com")!
}
SWIFT
  fi
  printf '%s' "$workspace"
}

# Runs step.sh, capturing combined output and exit code into globals.
run_step() {
  STEP_OUT="$(env "$@" bash "$STEP" 2>&1)"
  STEP_STATUS=$?
}

json_field() {
  node -e '
    const fs = require("fs");
    try {
      const r = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
      const path = process.argv[2].split(".");
      let v = r;
      for (const k of path) v = v?.[k];
      process.stdout.write(String(v));
    } catch { process.stdout.write("PARSE_ERROR"); }
  ' "$1" "$2" 2>/dev/null
}

skip_install_flag() {
  if [ "${FAST:-0}" = "1" ]; then echo "APPFLIGHT_STEP_SKIP_INSTALL=true"; else echo "APPFLIGHT_STEP_SKIP_INSTALL=false"; fi
}

bold "Appflight Bitrise step — end-to-end tests"
echo "step:   ${STEP}"
echo "pinned: ${PINNED_VERSION}"
echo "mode:   $([ "${FAST:-0}" = "1" ] && echo 'FAST (reuse PATH binary)' || echo 'full (npm install per case)')"
echo

# ─────────────────────────────────────────────────────────────────────────────
bold "1. Clean project passes and still writes the artifact"
ws="$(make_workspace clean-app)"
run_step "$(skip_install_flag)" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  fail_on="critical" \
  deep="false" \
  api_token=""

assert_eq 0 "$STEP_STATUS" "step exits 0"
assert_contains "$STEP_OUT" "PASSED" "log reports PASSED"
assert_file "${ws}/deploy/appflight-report.json" "JSON artifact written"
assert_eq "1.9" "$(json_field "${ws}/deploy/appflight-report.json" schemaVersion)" "published CLI emits schema 1.9"
assert_contains "$STEP_OUT" "APPFLIGHT_VERDICT=$(json_field "${ws}/deploy/appflight-report.json" verdict)" "real scan verdict exported"
assert_contains "$STEP_OUT" "APPFLIGHT_EVALUATION_STATUS=$(json_field "${ws}/deploy/appflight-report.json" evaluationStatus)" "real scan evaluation status exported"
assert_eq "0" "$(json_field "${ws}/deploy/appflight-report.json" summary.total)" "report total is 0"
assert_eq "false" "$(json_field "${ws}/deploy/appflight-report.json" gate.triggered)" "gate not triggered"
assert_contains "$STEP_OUT" "APPFLIGHT_FINDING_COUNT=0" "finding count exported"
assert_contains "$STEP_OUT" "no source code or project data is sent to Appflight" "local Appflight API boundary stated"
rm -rf "$ws"
echo

# ─────────────────────────────────────────────────────────────────────────────
bold "2. Critical finding fails the build with exit 1"
ws="$(make_workspace critical-app)"
run_step "$(skip_install_flag)" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  fail_on="critical" \
  deep="false" \
  api_token=""

assert_eq 1 "$STEP_STATUS" "step exits 1"
assert_contains "$STEP_OUT" "FAILED — findings at or above" "log reports the gate failing"
assert_contains "$STEP_OUT" "compliance gate working as configured" "failure is attributed to the gate"
assert_file "${ws}/deploy/appflight-report.json" "JSON artifact written on failure"
assert_eq "1" "$(json_field "${ws}/deploy/appflight-report.json" summary.total)" "report total is 1"
assert_eq "1" "$(json_field "${ws}/deploy/appflight-report.json" summary.critical)" "report critical is 1"
assert_eq "true" "$(json_field "${ws}/deploy/appflight-report.json" gate.triggered)" "gate triggered"
assert_contains "$STEP_OUT" "APPFLIGHT_FINDING_COUNT=1" "finding count exported on failure"
# The secret must never appear in the log or the artifact.
assert_contains "$STEP_OUT" "[REDACTED]" "secret is redacted in the log"
if grep -qF "$FAKE_SECRET" "${ws}/deploy/appflight-report.json"; then
  notok "raw secret leaked into the JSON artifact"
else
  ok "raw secret absent from the JSON artifact"
fi
rm -rf "$ws"
echo

# ─────────────────────────────────────────────────────────────────────────────
bold "3. fail_on=none is report-only: findings recorded, build still passes"
ws="$(make_workspace critical-app)"
run_step "$(skip_install_flag)" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  fail_on="none" \
  deep="false" \
  api_token=""

assert_eq 0 "$STEP_STATUS" "step exits 0 with fail_on=none"
assert_file "${ws}/deploy/appflight-report.json" "artifact still written"
assert_eq "1" "$(json_field "${ws}/deploy/appflight-report.json" summary.critical)" "critical finding still recorded"
rm -rf "$ws"
echo

# ─────────────────────────────────────────────────────────────────────────────
bold "4. deep=true without a token fails fast"
ws="$(make_workspace clean-app)"
run_step "$(skip_install_flag)" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  fail_on="critical" \
  deep="true" \
  api_token=""

assert_eq 1 "$STEP_STATUS" "step exits 1"
assert_contains "$STEP_OUT" "deep is 'true' but api_token is empty" "explains the misconfiguration"
assert_contains "$STEP_OUT" "appflight login --print-token" "tells the user how to get a token"
assert_no_file "${ws}/deploy/appflight-report.json" "no artifact written on a config error"
rm -rf "$ws"
echo

# ─────────────────────────────────────────────────────────────────────────────
bold "4b. deep=true rejects unresolved or malformed secret values"
ws="$(make_workspace clean-app)"

run_step "$(skip_install_flag)" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  fail_on="critical" \
  deep="true" \
  api_token='$APPFLIGHT_API_TOKEN'

assert_eq 1 "$STEP_STATUS" "unexpanded secret reference exits 1"
assert_contains "$STEP_OUT" "unexpanded environment-variable reference" "identifies Bitrise secret expansion"
assert_contains "$STEP_OUT" "Replace variables in inputs" "gives the Bitrise setting to enable"
assert_no_file "${ws}/deploy/appflight-report.json" "no artifact written for an unresolved secret"

run_step "$(skip_install_flag)" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  fail_on="critical" \
  deep="true" \
  api_token="not-an-appflight-token"

assert_eq 1 "$STEP_STATUS" "malformed token exits 1"
assert_contains "$STEP_OUT" "raw three-part token" "explains the accepted token shape"
rm -rf "$ws"
echo

bold "5. Invalid configuration is rejected before install"
ws="$(make_workspace clean-app)"

run_step BITRISE_DEPLOY_DIR="${ws}/deploy" project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" fail_on="banana" deep="false" api_token=""
assert_eq 1 "$STEP_STATUS" "bad fail_on exits 1"
assert_contains "$STEP_OUT" "fail_on must be one of" "names the valid values"

run_step BITRISE_DEPLOY_DIR="${ws}/deploy" project_path="${ws}/app" \
  appflight_version="latest" fail_on="critical" deep="false" api_token=""
assert_eq 1 "$STEP_STATUS" "appflight_version=latest is rejected"
assert_contains "$STEP_OUT" "must be an exact version" "explains why pinning is required"

run_step BITRISE_DEPLOY_DIR="${ws}/deploy" project_path="${ws}/does-not-exist" \
  appflight_version="$PINNED_VERSION" fail_on="critical" deep="false" api_token=""
assert_eq 1 "$STEP_STATUS" "missing project_path exits 1"
assert_contains "$STEP_OUT" "is not a directory" "explains the bad path"

run_step BITRISE_DEPLOY_DIR="${ws}/deploy" project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" fail_on="critical" deep="maybe" api_token=""
assert_eq 1 "$STEP_STATUS" "bad deep value exits 1"

run_step BITRISE_DEPLOY_DIR="${ws}/deploy" project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" platform="both" fail_on="critical" deep="false" api_token=""
assert_eq 1 "$STEP_STATUS" "bad platform exits 1"
assert_contains "$STEP_OUT" "platform must be one of" "names valid platform selectors"

run_step BITRISE_DEPLOY_DIR="${ws}/deploy" project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" platform="ios" android_variant="release" \
  fail_on="critical" deep="false" api_token=""
assert_eq 1 "$STEP_STATUS" "Android selector with platform=ios exits 1"
assert_contains "$STEP_OUT" "Android-only" "rejects cross-platform option mixing"
rm -rf "$ws"
echo

# ─────────────────────────────────────────────────────────────────────────────
bold "6. CLI exit 2 fails the build as a TOOL ERROR, never as clean"
ws="$(make_workspace clean-app)"
stub_dir="${ws}/stub"
mkdir -p "$stub_dir"
cat >"${stub_dir}/appflight" <<'STUB'
#!/usr/bin/env bash
# Stands in for a CLI that cannot complete the scan.
if [ "$1" = "version" ]; then echo "0.12.0"; exit 0; fi
echo "appflight check: scan failed: simulated tool error" >&2
exit 2
STUB
chmod +x "${stub_dir}/appflight"

run_step APPFLIGHT_STEP_SKIP_INSTALL=true \
  PATH="${stub_dir}:${PATH}" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  fail_on="critical" \
  deep="false" \
  api_token=""

assert_eq 1 "$STEP_STATUS" "tool error fails the build"
assert_contains "$STEP_OUT" "TOOL ERROR" "distinct TOOL ERROR label"
assert_contains "$STEP_OUT" "must not be read as one" "explicitly warns against reading it as clean"
assert_contains "$STEP_OUT" "APPFLIGHT_FINDING_COUNT=unknown" "finding count is 'unknown', not 0"
assert_no_file "${ws}/deploy/appflight-report.json" "empty report is removed, not left as a stub"
rm -rf "$ws"
echo

# ─────────────────────────────────────────────────────────────────────────────
bold "6b. deep=true injects api_token as APPFLIGHT_TOKEN for the CLI only"
ws="$(make_workspace clean-app)"
stub_dir="${ws}/stub"
mkdir -p "$stub_dir"
cat >"${stub_dir}/appflight" <<'STUB'
#!/usr/bin/env bash
if [ "$1" = "version" ]; then echo "0.12.0"; exit 0; fi
case " $* " in
  *" --deep "*)
    if [ "${APPFLIGHT_TOKEN:-}" != "header.payload.signature" ]; then
      echo "missing command-scoped APPFLIGHT_TOKEN" >&2
      exit 2
    fi
    printf '%s\n' '{"summary":{"total":0},"gate":{"triggered":false}}'
    ;;
  *)
    echo "deterministic stub"
    ;;
esac
exit 0
STUB
chmod +x "${stub_dir}/appflight"

run_step APPFLIGHT_STEP_SKIP_INSTALL=true \
  PATH="${stub_dir}:${PATH}" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  fail_on="critical" \
  deep="true" \
  api_token="header.payload.signature"

assert_eq 0 "$STEP_STATUS" "valid deep credential reaches the CLI"
assert_file "${ws}/deploy/appflight-report.json" "deep JSON artifact written"
assert_eq "0" "$(json_field "${ws}/deploy/appflight-report.json" summary.total)" "deep report is parsed"
rm -rf "$ws"
echo

bold "6c. Android selectors and execution disclosure reach both passes"
ws="$(make_workspace clean-app)"
stub_dir="${ws}/stub"
mkdir -p "$stub_dir"
cat >"${stub_dir}/appflight" <<'STUB'
#!/usr/bin/env bash
if [ "$1" = "version" ]; then echo "0.12.0"; exit 0; fi
printf '%s\n' "$*" >>"${APPFLIGHT_ARGS_LOG}"
case " $* " in
  *" --json "*) printf '%s\n' '{"summary":{"total":0},"gate":{"triggered":false}}' ;;
  *) echo "deterministic Android stub" ;;
esac
exit 0
STUB
chmod +x "${stub_dir}/appflight"

run_step APPFLIGHT_STEP_SKIP_INSTALL=true \
  APPFLIGHT_ARGS_LOG="${ws}/args.log" \
  PATH="${stub_dir}:${PATH}" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  platform="android" \
  android_module=":app" \
  android_variant="playRelease" \
  allow_gradle_network="true" \
  fail_on="warning" \
  deep="false" \
  api_token=""

assert_eq 0 "$STEP_STATUS" "Android passthrough step exits 0"
assert_contains "$STEP_OUT" "evaluates that build logic twice" "two Gradle evaluations are disclosed"
assert_eq 2 "$(wc -l <"${ws}/args.log" | tr -d ' ')" "CLI is invoked twice"
android_args="$(cat "${ws}/args.log")"
assert_contains "$android_args" "--platform android" "platform selector reaches the CLI"
assert_contains "$android_args" "--module :app" "module selector reaches the CLI"
assert_contains "$android_args" "--variant playRelease" "variant selector reaches the CLI"
assert_contains "$android_args" "--allow-gradle-network" "Gradle network opt-in reaches the CLI"
rm -rf "$ws"
echo

bold "6d. distribution is transported verbatim to both CLI invocations"
# The step's responsibility is transport, not semantics. What android.target_api
# finally reports for a given distribution is engine behaviour, proven end to end
# by the AppScan corpus at 9fef583 (Play repos: evaluated (evidence_available);
# NewPipe: not_applicable (non_play_distribution)). These stubs deliberately
# assert nothing about rule status.
for dist in google_play non_play; do
  ws="$(make_workspace clean-app)"
  stub_dir="${ws}/stub"
  mkdir -p "$stub_dir"
  cat >"${stub_dir}/appflight" <<'STUB'
#!/usr/bin/env bash
if [ "$1" = "version" ]; then echo "0.12.0"; exit 0; fi
printf '%s\n' "$*" >>"${APPFLIGHT_ARGS_LOG}"
case " $* " in
  *" --json "*) printf '%s\n' '{"summary":{"total":0},"gate":{"triggered":false}}' ;;
  *) echo "deterministic Android stub" ;;
esac
exit 0
STUB
  chmod +x "${stub_dir}/appflight"

  run_step APPFLIGHT_STEP_SKIP_INSTALL=true \
    APPFLIGHT_ARGS_LOG="${ws}/args.log" \
    PATH="${stub_dir}:${PATH}" \
    BITRISE_DEPLOY_DIR="${ws}/deploy" \
    project_path="${ws}/app" \
    appflight_version="$PINNED_VERSION" \
    platform="android" \
    distribution="$dist" \
    fail_on="critical" \
    deep="false" \
    api_token=""

  assert_eq 0 "$STEP_STATUS" "distribution=${dist} step exits 0"
  assert_eq 2 "$(wc -l <"${ws}/args.log" | tr -d ' ')" "distribution=${dist} invokes the CLI twice"
  # Both passes must carry it: the JSON pass is the one that gates the build.
  assert_eq 2 "$(grep -c -- "--distribution ${dist}" "${ws}/args.log")" \
    "distribution=${dist} reaches both deterministic and JSON passes"
  assert_contains "$(grep -- ' --json' "${ws}/args.log")" "--distribution ${dist}" \
    "distribution=${dist} present on the gating JSON pass"
  rm -rf "$ws"
done
echo

bold "6e. Omitted distribution forwards no --distribution argument"
ws="$(make_workspace clean-app)"
stub_dir="${ws}/stub"
mkdir -p "$stub_dir"
cat >"${stub_dir}/appflight" <<'STUB'
#!/usr/bin/env bash
if [ "$1" = "version" ]; then echo "0.12.0"; exit 0; fi
printf '%s\n' "$*" >>"${APPFLIGHT_ARGS_LOG}"
case " $* " in
  *" --json "*) printf '%s\n' '{"summary":{"total":0},"gate":{"triggered":false}}' ;;
  *) echo "deterministic Android stub" ;;
esac
exit 0
STUB
chmod +x "${stub_dir}/appflight"

run_step APPFLIGHT_STEP_SKIP_INSTALL=true \
  APPFLIGHT_ARGS_LOG="${ws}/args.log" \
  PATH="${stub_dir}:${PATH}" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  platform="android" \
  fail_on="critical" \
  deep="false" \
  api_token=""

assert_eq 0 "$STEP_STATUS" "omitted distribution step exits 0"
# No argument at all, rather than a defaulted one: the step must not decide that
# an Android project ships on Play. The CLI then leaves distribution-dependent
# rules unevaluated, which is the honest outcome.
assert_eq 0 "$(grep -c -- "--distribution" "${ws}/args.log")" \
  "no --distribution argument is synthesised"
rm -rf "$ws"
echo

bold "6f. Invalid and cross-platform distribution values are refused"
ws="$(make_workspace clean-app)"

run_step BITRISE_DEPLOY_DIR="${ws}/deploy" project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" platform="android" distribution="sideloaded" \
  fail_on="critical" deep="false" api_token=""
assert_eq 1 "$STEP_STATUS" "unsupported distribution exits 1"
assert_contains "$STEP_OUT" "distribution must be empty, google_play or non_play" \
  "names the supported distribution values"

run_step BITRISE_DEPLOY_DIR="${ws}/deploy" project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" platform="ios" distribution="google_play" \
  fail_on="critical" deep="false" api_token=""
assert_eq 1 "$STEP_STATUS" "distribution with platform=ios exits 1"
assert_contains "$STEP_OUT" "Android-only" "rejects distribution on iOS"
rm -rf "$ws"
echo

bold "6g. The Gradle execution disclosure matches the invocation"
# D1/D2: the disclosure is a security statement, so it must appear exactly when
# Android execution is possible and must describe the run it precedes. The Step
# never predicts the platform; platform=auto still warns because it may resolve
# to Android, and the wording says "may execute" for that reason.
disclosure_stub() {
  local dir="$1"
  mkdir -p "$dir"
  cat >"${dir}/appflight" <<'STUB'
#!/usr/bin/env bash
if [ "$1" = "version" ]; then echo "0.12.0"; exit 0; fi
case " $* " in
  *" --json "*) printf '%s\n' '{"summary":{"total":0},"gate":{"triggered":false}}' ;;
  *) echo "deterministic stub" ;;
esac
exit 0
STUB
  chmod +x "${dir}/appflight"
}

# platform=ios: Android execution cannot happen, so the disclosure must be absent.
ws="$(make_workspace clean-app)"
disclosure_stub "${ws}/stub"
run_step APPFLIGHT_STEP_SKIP_INSTALL=true PATH="${ws}/stub:${PATH}" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" platform="ios" \
  fail_on="critical" deep="false" api_token=""
assert_eq 0 "$STEP_STATUS" "platform=ios step exits 0"
assert_not_contains "$STEP_OUT" "Android note" "no Android disclosure on an iOS build"
assert_not_contains "$STEP_OUT" "may execute the repository Gradle wrapper" \
  "no Gradle execution claim on an iOS build"
rm -rf "$ws"

# platform=android, offline: the disclosure must describe this run, not a default.
ws="$(make_workspace clean-app)"
disclosure_stub "${ws}/stub"
run_step APPFLIGHT_STEP_SKIP_INSTALL=true PATH="${ws}/stub:${PATH}" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" platform="android" allow_gradle_network="false" \
  fail_on="critical" deep="false" api_token=""
assert_eq 0 "$STEP_STATUS" "platform=android offline step exits 0"
assert_contains "$STEP_OUT" "may execute the repository Gradle wrapper" \
  "Android build discloses possible Gradle execution"
assert_contains "$STEP_OUT" "Gradle dependency resolution is offline for this run" \
  "offline run is described as offline"
assert_not_contains "$STEP_OUT" "network resolution is enabled for this run" \
  "offline run does not claim network resolution"
assert_contains "$STEP_OUT" "gradle net   : false" "raw setting still shown"
rm -rf "$ws"

# platform=android, network enabled: the wording must flip with the setting.
ws="$(make_workspace clean-app)"
disclosure_stub "${ws}/stub"
run_step APPFLIGHT_STEP_SKIP_INSTALL=true PATH="${ws}/stub:${PATH}" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" platform="android" allow_gradle_network="true" \
  fail_on="critical" deep="false" api_token=""
assert_eq 0 "$STEP_STATUS" "platform=android networked step exits 0"
assert_contains "$STEP_OUT" "Gradle dependency network resolution is enabled for this run" \
  "networked run is described as networked"
assert_not_contains "$STEP_OUT" "resolution is offline for this run" \
  "networked run does not claim to be offline"
assert_contains "$STEP_OUT" "gradle net   : true" "raw setting still shown"
rm -rf "$ws"

# platform=auto: warn before discovery, without asserting which platform wins.
ws="$(make_workspace clean-app)"
disclosure_stub "${ws}/stub"
run_step APPFLIGHT_STEP_SKIP_INSTALL=true PATH="${ws}/stub:${PATH}" \
  BITRISE_DEPLOY_DIR="${ws}/deploy" project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" platform="auto" \
  fail_on="critical" deep="false" api_token=""
assert_eq 0 "$STEP_STATUS" "platform=auto step exits 0"
assert_contains "$STEP_OUT" "may execute the repository Gradle wrapper" \
  "auto warns before discovery resolves the platform"
assert_contains "$STEP_OUT" "platform     : auto" "auto is reported as unresolved"
# The Step must not claim to know the outcome discovery has not reached yet.
assert_not_contains "$STEP_OUT" "Android project detected" "auto does not assert a platform"
rm -rf "$ws"
echo

bold "6h. prove_billing reaches Android scans only, on a CLI that has the flag"
# The CLI rejects --prove-billing for iOS (exit 2), so a default-on input must
# never reach an iOS scan, and a pre-0.12.0 pin must not receive an unknown flag.
billing_case() {
  # $1 = description, remaining = extra env for the step
  local what="$1"; shift
  ws="$(make_workspace clean-app)"
  mkdir -p "${ws}/stub"
  cat >"${ws}/stub/appflight" <<'STUB'
#!/usr/bin/env bash
if [ "$1" = "version" ]; then echo "0.12.0"; exit 0; fi
printf '%s\n' "$*" >>"${APPFLIGHT_ARGS_LOG}"
case " $* " in
  *" --json "*) printf '%s\n' '{"summary":{"total":0},"gate":{"triggered":false}}' ;;
  *) echo "deterministic stub" ;;
esac
exit 0
STUB
  chmod +x "${ws}/stub/appflight"
  : >"${ws}/args.log"
  run_step APPFLIGHT_STEP_SKIP_INSTALL=true APPFLIGHT_ARGS_LOG="${ws}/args.log" \
    PATH="${ws}/stub:${PATH}" BITRISE_DEPLOY_DIR="${ws}/deploy" project_path="${ws}/app" \
    fail_on="critical" deep="false" api_token="" "$@"
  BILLING_ARGS="$(cat "${ws}/args.log")"
  echo "    (${what})"
}

billing_case "android, default on" appflight_version="$PINNED_VERSION" platform="android"
assert_eq 0 "$STEP_STATUS" "android default step exits 0"
assert_eq 2 "$(grep -c -- "--prove-billing" "${ws}/args.log")" "--prove-billing reaches both passes by default"
assert_not_contains "$BILLING_ARGS" "--billing-closure-timeout" "no timeout flag when the input is empty"
assert_contains "$STEP_OUT" "Billing proof: on" "the compile is disclosed before it runs"
rm -rf "$ws"

billing_case "android, timeout 25" appflight_version="$PINNED_VERSION" platform="android" billing_closure_timeout_minutes="25"
assert_eq 2 "$(grep -c -- "--prove-billing --billing-closure-timeout 25" "${ws}/args.log")" "timeout reaches both passes"
assert_contains "$STEP_OUT" "limit 25 min per pass" "the limit is disclosed"
rm -rf "$ws"

billing_case "android, opted out" appflight_version="$PINNED_VERSION" platform="android" prove_billing="no"
assert_eq 0 "$STEP_STATUS" "opted-out step exits 0"
assert_not_contains "$BILLING_ARGS" "--prove-billing" "prove_billing=no forwards nothing"
rm -rf "$ws"

billing_case "ios, default on" appflight_version="$PINNED_VERSION" platform="ios"
assert_eq 0 "$STEP_STATUS" "platform=ios with default prove_billing exits 0"
assert_not_contains "$BILLING_ARGS" "--prove-billing" "iOS never receives --prove-billing"
assert_not_contains "$STEP_OUT" "Billing proof" "iOS build does not mention the Billing compile"
rm -rf "$ws"

billing_case "auto, no Gradle wrapper" appflight_version="$PINNED_VERSION" platform="auto"
assert_not_contains "$BILLING_ARGS" "--prove-billing" "auto without gradlew forwards nothing"
rm -rf "$ws"

ws_auto="$(make_workspace clean-app)"; touch "${ws_auto}/app/gradlew"
billing_case "auto, Gradle wrapper present" appflight_version="$PINNED_VERSION" platform="auto" project_path="${ws_auto}/app"
assert_eq 2 "$(grep -c -- "--prove-billing" "${ws}/args.log")" "auto with gradlew forwards --prove-billing"
rm -rf "$ws" "$ws_auto"

billing_case "android, CLI pinned below 0.12.0" appflight_version="0.11.0" platform="android"
assert_eq 0 "$STEP_STATUS" "old pin still runs"
assert_not_contains "$BILLING_ARGS" "--prove-billing" "old pin never receives an unknown flag"
assert_contains "$STEP_OUT" "prove_billing needs appflight 0.12.0+" "old pin is warned about"
rm -rf "$ws"

billing_case "invalid prove_billing" appflight_version="$PINNED_VERSION" platform="android" prove_billing="true"
assert_eq 1 "$STEP_STATUS" "prove_billing=true is refused"
assert_contains "$STEP_OUT" "prove_billing must be 'yes' or 'no'" "names the accepted values"
rm -rf "$ws"

billing_case "invalid timeout" appflight_version="$PINNED_VERSION" platform="android" billing_closure_timeout_minutes="15m"
assert_eq 1 "$STEP_STATUS" "non-numeric timeout is refused"
assert_contains "$STEP_OUT" "billing_closure_timeout_minutes must be a number" "explains the timeout format"
rm -rf "$ws"
echo

bold "6i. form_factors reaches Android scans only, on a CLI that has the flag"
billing_case "android, phone,wear" appflight_version="$PINNED_VERSION" platform="android" form_factors="phone,wear"
assert_eq 0 "$STEP_STATUS" "form_factors step exits 0"
assert_eq 2 "$(grep -c -- "--form-factors phone,wear" "${ws}/args.log")" "form_factors reaches both passes"
rm -rf "$ws"

billing_case "android, empty" appflight_version="$PINNED_VERSION" platform="android"
assert_not_contains "$BILLING_ARGS" "--form-factors" "empty form_factors forwards nothing (never assumed)"
rm -rf "$ws"

billing_case "ios" appflight_version="$PINNED_VERSION" platform="ios" form_factors="phone"
assert_eq 1 "$STEP_STATUS" "form_factors with platform=ios exits 1"
assert_contains "$STEP_OUT" "Android-only" "rejects form_factors on iOS"
rm -rf "$ws"

billing_case "auto, no Gradle wrapper" appflight_version="$PINNED_VERSION" platform="auto" form_factors="phone"
assert_not_contains "$BILLING_ARGS" "--form-factors" "auto without gradlew withholds form_factors"
assert_contains "$STEP_OUT" "form_factors is Android-only" "and says why"
rm -rf "$ws"

billing_case "android, CLI pinned below 0.12.0" appflight_version="0.11.0" platform="android" form_factors="phone"
assert_not_contains "$BILLING_ARGS" "--form-factors" "old pin never receives --form-factors"
assert_contains "$STEP_OUT" "declare formFactors in policy_context_file instead" "old pin points at the file"
rm -rf "$ws"

for bad in "watch" "phone, wear" "phone,"; do
  billing_case "invalid '${bad}'" appflight_version="$PINNED_VERSION" platform="android" form_factors="$bad"
  assert_eq 1 "$STEP_STATUS" "form_factors='${bad}' is refused"
  assert_contains "$STEP_OUT" "form_factors must be a comma-separated list" "names the accepted values for '${bad}'"
  rm -rf "$ws"
done
echo

bold "7. Missing BITRISE_DEPLOY_DIR degrades with a warning"
ws="$(make_workspace clean-app)"
pushd "$ws" >/dev/null
run_step "$(skip_install_flag)" \
  project_path="${ws}/app" \
  appflight_version="$PINNED_VERSION" \
  fail_on="critical" \
  deep="false" \
  api_token=""
popd >/dev/null

assert_eq 0 "$STEP_STATUS" "step still completes"
assert_contains "$STEP_OUT" "BITRISE_DEPLOY_DIR is not set" "warns the artifact will not be exported"
rm -rf "$ws"
echo

# ─────────────────────────────────────────────────────────────────────────────
bold "8. Schema 1.9 scope is independent of the severity gate"
for scenario in partial-empty partial-findings unknown legacy complete; do
  ws="$(make_workspace clean-app)"
  mkdir -p "${ws}/stub"
  cat >"${ws}/stub/appflight" <<'STUB'
#!/usr/bin/env bash
if [ "$1" = "version" ]; then echo "0.12.0"; exit 0; fi
case " $* " in
  *" --json "*)
    case "$SCOPE_SCENARIO" in
      partial-empty) echo '{"schemaVersion":"1.9","verdict":"not_fully_evaluated","evaluationStatus":"incomplete","scope":{"status":"incomplete"},"summary":{"total":0},"risk_score":null}' ;;
      partial-findings) echo '{"schemaVersion":"1.9","verdict":"not_fully_evaluated","evaluationStatus":"incomplete","scope":{"status":"incomplete"},"summary":{"total":1},"findings":[{"severity":"CRITICAL","rule":{"execution":"enabled","validation":"unvalidated"}}]}' ;;
      unknown) echo '{"schemaVersion":"1.9","verdict":"not_fully_evaluated","evaluationStatus":"unknown","scope":{"status":"unknown"},"summary":{"total":0}}' ;;
      legacy) echo '{"summary":{"total":0}}' ;;
      complete) echo '{"schemaVersion":"1.9","verdict":"clear","evaluationStatus":"complete","scope":{"status":"complete"},"summary":{"total":0},"coverage":{"benchmarkValidationComplete":false}}' ;;
    esac ;;
  *) echo "stub deterministic output" ;;
esac
if [ "$SCOPE_SCENARIO" = "partial-findings" ]; then exit 1; fi
exit 0
STUB
  chmod +x "${ws}/stub/appflight"
  run_step APPFLIGHT_STEP_SKIP_INSTALL=true PATH="${ws}/stub:${PATH}" SCOPE_SCENARIO="$scenario" \
    BITRISE_DEPLOY_DIR="${ws}/deploy" project_path="${ws}/app" \
    appflight_version="$PINNED_VERSION" platform="ios" fail_on="critical" deep="false" api_token=""
  if [ "$scenario" = "partial-findings" ]; then
    assert_eq 1 "$STEP_STATUS" "observed critical finding still fails incomplete analysis"
    assert_contains "$STEP_OUT" "APPFLIGHT_FINDING_COUNT=1" "observed finding count survives"
  else
    assert_eq 0 "$STEP_STATUS" "${scenario}: finding gate still passes"
    assert_contains "$STEP_OUT" "finding threshold only" "${scenario}: pass is qualified"
  fi
  if [ "$scenario" = "complete" ]; then
    assert_contains "$STEP_OUT" "APPFLIGHT_EVALUATION_STATUS=complete" "explicit complete scope survives unvalidated benchmark metadata"
    assert_contains "$STEP_OUT" "APPFLIGHT_VERDICT=clear" "explicit clear verdict exported"
    assert_not_contains "$STEP_OUT" "More findings may exist" "no false incomplete scope for complete report"
  else
    assert_contains "$STEP_OUT" "not a clean result" "${scenario}: no false clean claim"
    assert_contains "$STEP_OUT" "More findings may exist" "${scenario}: absence not conclusive"
    if [ "$scenario" = "unknown" ] || [ "$scenario" = "legacy" ]; then
      assert_contains "$STEP_OUT" "APPFLIGHT_EVALUATION_STATUS=unknown" "${scenario}: scope remains unknown"
    else
      assert_contains "$STEP_OUT" "APPFLIGHT_EVALUATION_STATUS=incomplete" "${scenario}: incomplete state exported"
    fi
    if [ "$scenario" != "legacy" ]; then
      assert_contains "$STEP_OUT" "APPFLIGHT_VERDICT=not_fully_evaluated" "${scenario}: partial verdict exported"
    fi
  fi
  assert_file "${ws}/deploy/appflight-report.json" "${scenario}: original report retained"
  rm -rf "$ws"
done
echo

rule="========================================================"
echo "$rule"
if [ "$fail_count" -eq 0 ]; then
  green "ALL ASSERTIONS PASSED  (${pass_count} assertions)"
  echo "$rule"
  exit 0
fi
red "FAILURES: ${fail_count} failed, ${pass_count} passed"
echo "$rule"
exit 1
